apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: echo-message-pipeline
spec:
  params:
    - name: message-text
      type: string
  tasks:
    - name: echo
      taskRef:
        name: echo-message-task
      params:
        - name: message-text
          value: "$(params.message-text)"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: "main"
  tasks: 
    - name: clone
      taskRef:
        name: checkout-task
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"

    - name: lint
      taskRef:
        name: echo-message-task
      params:
        - name: message-text
          value: "Calling Flake8 linter..."
      runAfter:
        - clone

    - name: tests
      taskRef:
        name: echo-message-task
      params:
        - name: message-text
          value: "Running unit tests with PyUnit..."
      runAfter:
        - lint

    - name: build
      taskRef:
        name: echo-message-task
      params:
        - name: message-text
          value: "Building image for $(params.repo-url)..."
      runAfter:
        - tests

    - name: deploy
      taskRef:
        name: echo-message-task
      params:
        - name: message-text
          value: "Deploying $(params.branch) branch of $(params.repo-url)..."
      runAfter:
        - build